### PR TITLE
chore: add CI and release actions

### PR DESCRIPTION
**Pull request by Feichtmeier**

### CODE REVIEW

**Comment by ClementBeal** [comment]
Thank you for the PR!

Just to be sure and to understand the workflow :

- if we create a PR, it checks the formatting, run the tests and the linter
- if we push code to `main`, we create a new release in Github?

**Comment by Feichtmeier** [comment]
The one workflow creates three containers (jobs) and inside
Checks if format is correct
Checks if analyze is correct
Checks if tests pass (if you have a test directory) 

The other for release creates you need to do the following: 

All commits must have prefixes like

fix: bla
feat: blub
chore: bleep

Or for breaking changes add an ! before : like so

feat!: new API bla blub

or

fix!: blurp blap

Then the workflow creates a new PR or updates a three pending pr it created already and updates it via force push
The pr itself only has two changes: 
- updated change log
- version bumped according to your commits (minor or major version )

Then you can decide when you want to merge the pr

After you merged it you need to pull from main on your computer and just do the dart pub publish like always

**Comment by Feichtmeier** [comment]
You also need to add the actions to required in there branches in your settings

**Comment by Feichtmeier** [comment]
@ClementBeal 
if you only one one of the actions I can remove it or put it in a different PR?

independant of this I would just suggest that if you make a breaking change I would bumpt a major version instead of minor, this way people are guarded by the pub upgrading mechanism

**Comment by ClementBeal** [comment]
I want both!

I just need to fix a bug before merging your PR otherwise I "can't" deploy anything else.

**Comment by ClementBeal** [comment]
I merge it. Thank you!

**Pull request merged**
